Task_1_1_2
yura-poj/OOP pull request #15
Opened 2024-09-09 16:28 UTC by yura-poj

Это не совсем готовая версия, я не понял что писать в тестах и доки потом напишу, так в целом с кодом все норм?

2024-09-10 05:51 UTC, galinabykova requested changes
мягкий дедлайн засчитываю, ты значительно продвинулся в решении

Для первого решения - хорошо.
У тебя в коде повторяется одна и та же ошибка: ты позволяешь классам менять поля друг друга. Это очень сильно затрудняет читаемость и плохо с точки зрения расширяемости, как я писала ранее. Поэтому, пожалуйста, исправь это, потом я досмотрю код. 

Скорее всего, в будущей версии у меня будет ещё много замечаний, так что сильно не затягивай.

По поводу тестов - тебе нужно протестировать публичное апи всех классов, за исключением геттеров и чего-то такого же простого. 
 
Также можно максимально разнести вывод в консоль и логику и проверять состояние, либо как-то в тестах задавать и получать стандартный ввод-вывод. Тут есть два варианта - во-первых, ты можешь принимать в конструкторах классов InputStream, OutputStream, в которые надо писать (и просто в точке main прописать, что читать надо из System.in, а писать в System.out), а можно прямо в тесте перехватить System.in-System.out. например, так 

https://ru.stackoverflow.com/questions/1309167/junit-%D1%82%D0%B5%D1%81%D1%82-%D1%81-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%BC-%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D1%8E%D1%89%D0%B8%D0%BC-scanner-system-in

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +        int numberOpenedCards = 0;
в названии переменной неочевидно, что это число открытых карт дилера

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Dealer.java
> +    public void showCards(int numberOpenedCards) {
то, что число карт начинается с 0 не совсем очевидное поведение. Такие особенности поведения лучше описывать в документации, не забудь это сделать)

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +    private void statistics() {
мне кажется, это не просто статистика, а вывод статистики. Мне кажется, это лучше отобразить в названии, showStatistics

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +    boolean stop = false;
лучше сделать private

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +    public void step() {
расставь модификаторы доступа осмысленно

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Player.java
> +    Card current_card;
У каждой абстракции есть поведение и реализация. Поведение - то, что, как мы надеемся, либо не будет меняться, либо будет меняться достаточно редко. Реализация, в отличие от поведения, меняется достаточно часто, поэтому мы стремимся, чтобы наши абстракции не зависили от реализаций друг друга.

Поле класса - это деталь реализации, поэтому мы стараемся не открывать к нему доступ из других классов. Не static final поля рекомендуется делать private. Если доступ к полю часть поведения класса, лучше сделать геттер или сеттер. В этом случае, ты сможешь потом менять реализацию.

Подробнее можно почитать, например, [тут](https://javarush.com/groups/posts/1928-getterih-i-setterih)

Кстати, это поле по сути не нужно. Достаточно сделать метод, в котором ты будешь возвращать последний элемент массива cards.

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +    public String getCardInfo(Card card) {
мне кажется, это метод должен быть в классе Card. Здесь ты никак не используешь Deck, этот метод относиться к карте и использует только состояние карты

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +    public String getCardInfo(Card card) {
удобно будет переопределить в Card toString

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Dealer.java
> +        if (points <= 17) {
лучше сделать static final  поле для 17, чтобы было понятно, что это за магическая константа

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +        int numberOpenedCards = 0;
а вообще, мне кажется, что ты можешь хранить как часть состояния дилера флажок о том, чья сейчас очередь. Мне просто не нравится, что рабочий стол думает о том, сколько карт дилер показывает

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +            if (chose == 0) {
тут можно switch-case использовать, мне кажется, будет читаемее

2024-09-10 05:51 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Player.java
> +    int score = 0;
Player никогда сам не меняет и никогда не использует это поле. Мне кажется, оно не должно быть здесь

2024-09-11 12:58 UTC, yura-poj commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Player.java
> +    int score = 0;
Касаемо Player: Это класс имитирующий действия и состояния игрока( то есть что он может делать в игре и то что у него условно лежит на столе , предположим что у игрока на столе лежит счетчик его побед, он лежит на его столе, но виден всем) как то так, если вы так не считаете могу изменить) ,ну и вот джавадок /**
 * class that imitate action and state of real player.
 * such action as: get card from deck, stop getting new card,
 * remove old cards and start new game.
 * such states as: score of wins, sum of points of the cards.
 */

2024-09-11 16:16 UTC, galinabykova requested changes
не забудь тестики)

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +    public Card give_card() {
мне кажется, удобнее было бы создать колоду, перемешать её в случайном порядке и доставать из перемешанной колоды карты последовательно. Это более затратное по памяти решение, но колода маленькая, так что памяти всё равно мало затронем, а по времени - константа

твоё решение меня смущает тем, что генерировать 52-ю карту можно долго. Но ты можешь не согласиться с этим)

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +        return new Card(names[id], score, suits[suit]);
мне кажется, score можно в карте посчитать, так как это свойство карты

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +    public Card give_card() {
и это не основная штука в этой лабе, так что можно не тратить время на изменение

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +        for (int i = 0; i < 13; i++) {
тут и в других местах кода избавься от магических констант) непонятно, откуда взялось 13, наверно можно взять длину массива с именами карт или сделать отдельную переменную с понятным названием

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +                System.out.println("Dealer open card: " + dealer.getCurrentCard().toString());
а попробуй убрать тут toString

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +                System.out.println("Dealer open card: " + dealer.getCurrentCard().toString());
если будет ошибка компиляции, напиши об этом)

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +        int gameResult = 0;
предлагаю для gameResult сделать Enum

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Player.java
> +    protected boolean stop = false;
лучше, когда у тебя поля и методы не смешиваются друг с другом, сначала идут поля, потом методы. Чтобы можно было посмотреть в начало класса и быть уверенным, что других полей нет

2024-09-11 16:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Player.java
> +    int score = 0;
хорошо)

2024-09-12 06:52 UTC, yura-poj commented
Все что сказали исправил, не стал только с колодой заморачиваться.

2024-09-12 08:41 UTC, galinabykova requested changes

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Card.java
> +    public Card(String name, int id, String suit) {
мне не нравится, что у тебя тут передаётся id: ну, просто это совсем не очевидная штука. Может вместо массива сделать словать (мапку), в которой каждому name будет сопоставлен свой points?

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +    public static final int NAMES_PER_DECK = 13;
эта штука привязана к names, так что я бы её вычисляла как names.length. Чтобы если число карт изменится, не надо было менять и тут чиселку

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +    public static final int NAMES_PER_DECK = 13;
и эта штука только в этом классе используется, поэтому её можно сделать private

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Deck.java
> +    private final String[] names = {"2", "3", "4", "5", "6", "7", "8", "9", "10",
сюда можно добавить static

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/pozhidaev/DeckTest.java
> +            card.toString();
кажется, это строчка ничего не делает

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +                System.out.println("Unknown result");
вроде тут можно убрать default, ты никогда сюда не попадёшь, у gameResult три значения

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +        if (user.getPoints() > 21 && dealer.getPoints() > 21) {
убери, пожалуйста, магические константы по всему коду)

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +        switch (gameResult) {
Это switch case можно полностью убрать с помощью такой штуки

```java
public class HelloWorld{
     private static enum GameResults {
        WIN("LYA"),
        LOSE("MYA"),
        DRAW("NYA");
        
        private String message;
        
        GameResults(String message) {
            this.message = message;
        }
        
        @Override
        public String toString() {
            return this.message;
        }
    }
    
     public static void main(String []args){
        GameResults res = GameResults.WIN;
        System.out.println(res);
     }
}
```

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Blackjack.java
> +    static Desktop desktop;
вроде ты используешь это только в main, мне кажется, в этом случае не надо выносить эти детали в поля

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/pozhidaev/DealerTest.java
> +        assertTimeout(ofMillis(10), () -> dealer.showCards());
прикольно, а можешь кратко прокомментировать зачем?)

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Dealer.java
> +    private static final int maxPointsNumber = 17;
посмотри, как в нашем стиле кода именуются константы)
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Dealer.java
> +    private static final int maxPointsNumber = 17;
а, ты вроде так их и именовал, наверно тут просто просмотрел)

2024-09-12 08:41 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +                switch (userInput) {
у тебя здесь значения userInput договорённость, я люблю прятать такие договорённости в Enum, чтобы потом в switch case использовать enum или  делать static final, но у тебя тут в целом из кода понятно, что такое 0 и 1, потому что в case читаемые названия методов, так что можно не менять, просто посмотри примерчик кода)
```java
public class HelloWorld{
     private static enum UserReply {
        ONE,
        TWO,
        THREE;
        
        public static UserReply fromInteger(int x) {
            switch(x) {
            case -1:
                return ONE;
            case 0:
                return TWO;
            case 1:
                return THREE;
            }
            return null;
        }
    }
    
     public static void main(String []args){
        UserReply res = UserReply.fromInteger(-1);
        System.out.println(res);
     }
}
```

2024-09-12 09:25 UTC, yura-poj commented on Task_1_1_2/src/test/java/ru/nsu/pozhidaev/DealerTest.java
> +        assertTimeout(ofMillis(10), () -> dealer.showCards());
ну эти поля могут часто меняться и как мне кажется целесообразней просто проверить что функция не зависла и работает, 10 милисикунд даже много тут милисикунды в целом хватит

2024-09-12 09:25 UTC, yura-poj commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Dealer.java
> +    private static final int maxPointsNumber = 17;
да, проглядел

2024-09-12 09:27 UTC, yura-poj commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +                switch (userInput) {
хорошо, запомню, а для чего? Мы можем в enam вызов другой функции засунуть? или просто чтобы было читабельней

2024-09-12 09:31 UTC, yura-poj commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +                System.out.println("Unknown result");
сodestyle ругается, до этого у меня не было default)

2024-09-12 10:16 UTC, yura-poj commented on Task_1_1_2/src/test/java/ru/nsu/pozhidaev/DeckTest.java
> +            card.toString();
забыл убрать

2024-09-12 10:41 UTC, yura-poj commented
исправления принял, кодстайл идеальный :D

2024-09-12 14:05 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/pozhidaev/DesktopTest.java
> +        while (points <= 21) {
в тестиках тоже надо убрать магические константы)

2024-09-12 14:05 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/pozhidaev/Desktop.java
> +                switch (userInput) {
просто, чтобы читабельней)

2024-09-12 14:10 UTC, galinabykova approved these changes
Добавила несколько не особо важных комментариев, исправлять не надо, просто посмотри

2024-09-12 14:10 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/pozhidaev/CardTest.java
> +class CardTest {
тут можно было побольше тестов, например, туз ещё

2024-09-12 14:28 UTC, yura-poj commented on Task_1_1_2/src/test/java/ru/nsu/pozhidaev/DesktopTest.java
> +        while (points <= 21) {
Тяжело редактировать уже написанный код) При написании следующей лабы, постараюсь держать в голове.

2024-09-16 10:20 UTC, merged