Task_1_1_3
yura-poj/OOP pull request #17
Opened 2024-09-19 05:53 UTC by yura-poj

2024-09-19 06:42 UTC, galinabykova requested changes
мягкий засчитан

2024-09-19 06:42 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Expression.java
> +    public abstract String toString();
обрати внимание, что метод toString есть в Object
https://www.examclouds.com/ru/java/java-core-russian/method-tostring
но объявление метода здесь имеет смысл, так как ты обязуешь своих наследников переопределить этот метод

2024-09-19 06:42 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Expression.java
> +        System.out.println(toString());
аналогичный результат можно получить, если в тело написать 
`System.out.println(this);`
потому что println вызывает у объектов метод toString

2024-09-19 06:42 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Expression.java
> +        System.out.println(toString());
возможно этот метод лишний, так как нужная тебе функциональность защита в toString, но это на твоё усмотрение

2024-09-19 06:42 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Div.java
> +    Expression left;
кажется, можно сделать private тут и везде

2024-09-19 06:42 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Variable.java
> +    public void setValue(String str) {
мне кажется, не очень хорошо, что ты протаскиваешь строку вплоть до переменной и парсишь её тут. Если в выражении будет тысяча переменных, ты тысячу раз будешь парсить словарь. Мне кажется, более удобно было бы сделать так:
1. в Expression сделать абстрактный метод evaluate(Map<String,String>)
2. переопределить его во всех наследниках
3. написать в Expression метод evaluate(String), в котором мы парсим строку в словарь и вызвать evaluate(Map<String,String>)
Тогда парсинг будет происходить единожды.

Предлагаю тебе либо переделать так код, либо доказать, что у твоего решения есть плюсы в сравнении с предложенным мной

2024-09-19 06:42 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Variable.java
> +    private int value;
не поняла, почему эта переменная часть состояния. Кажется, что означивание не является частью выражения, исходя из условия задачи

2024-09-19 07:08 UTC, yura-poj commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Variable.java
> +    private int value;
Вы имеете ввиду что value лишнее?

2024-09-19 07:10 UTC, yura-poj commented
а надо чтобы пользователь как то с консолью взаимодействовал? Это просто не написано

2024-09-19 07:12 UTC, yura-poj commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Variable.java
> +    public void setValue(String str) {
Хорошая идея, не совсем понял, сделать static map переменную внутри абстрактного класса и написать внутри него парсер и функцию которая выдает значение?

2024-09-19 07:30 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Variable.java
> +    public void setValue(String str) {
Не, сделать публичный метод evaluate, принимающий строку, в абстрактном классе, который будет парсить строку и вызывать абстрактный метод evaluate, принимающий мапу.

```java
abstract class Expression {
    //...
    
    public double eval(String s) {
        return evaluate(stringToMap(s));
    }
    
    private HashMap<String, Double> stringToMap(String s) {
        // ...
        return new HashMap<String, Double>();
    }
    
    abstract protected double evaluate(HashMap<String, Double> dict);
}

class Value extends Expression {
    private String name;
    
    @Override
    protected double evaluate(HashMap<String, Double> dict) {
        return dict.get(name);
    }
}

class Mul extends Expression {
    private Expression left;
    private Expression right;
    
    @Override
    protected double evaluate(HashMap<String, Double> dict) {
        return left.evaluate(dict) + right.evaluate(dict);
    }
}
```

2024-09-19 07:31 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Variable.java
> +    public void setValue(String str) {
в этом случае мы будем парсить строку один раз в абстрактном методе, а дальше передавать словарь

2024-09-19 07:31 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/pozhidaev/Variable.java
> +    private int value;
ага

2024-09-20 04:21 UTC, galinabykova requested changes
не увидела у тебя реализацию вот этого пункта
![image](https://github.com/user-attachments/assets/e7740bd2-2d91-4bd8-b142-399939a21755)
если пропустила что-то, подскажи, где оно, или реализуй)

2024-09-20 07:40 UTC, galinabykova approved these changes

2024-09-20 07:40 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/pozhidaev/ParserTest.java
тут можно было бы сделать больше тестов, крайние случаи рассмотреть и т.д.

2024-09-20 08:47 UTC, merged