Task_1_2_1
yura-poj/OOP pull request #18
Opened 2024-09-22 06:57 UTC by yura-poj

2024-09-22 12:12 UTC, galinabykova requested changes
ты сделал немного не то, что нужно сделать в этой задаче. Интерфейс Graph должен быть не классом, а интерфейсом (это особое понятие в Java), и у него должно быть три РЕАЛИЗАЦИИ, три отдельных класса, implements Graph. И внутри этих классов граф должен храниться как список смежности, матрица инцидентности и т.д.

А сортировка должна работать с любым типом, реализующим интерфейс Graph

2024-09-22 12:12 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/Edge.java
> +    Vertex from;
сделай все поля private

2024-09-22 12:12 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/Vertex.java
> +public class Vertex {
нужно, чтобы твой граф мог работать с любыми объектами, которые могут сравниваться. Поэтому этот тип должен быть параметризован, и принимать только Comparable (погугли generic)

2024-09-25 12:29 UTC, yura-poj commented
в правильном направлении двигаюсь?

2024-09-25 15:16 UTC, galinabykova requested changes
ага, направление верное)

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/Graph.java
> +public interface Graph {
параметризированный тип должен и сюда просочиться. Граф должен принимать вершины с произвольным типом внутри

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +    public void removeVertex(Vertex<String> vertex) {
обычно при  удалении вершины, удаляются и её рёбра, но, может, у тебя другая логика

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +        return vertices;
лучше клонировать список, чтобы нельзя было менять внутренность твоего графа. Тут ты отдаёшь ссылку на поле

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +    public boolean equals(Object o) {
при переопределении equals переопределяется hashCode (так в документации написано)

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +    private Scanner scanner;
мне очень сильно не нравится, что у тебя тут scanner является полем, ведь он не является частью графа по сути. При парсинге в любом случае инициализируешь scanner, а в  newLine можно передать scanner как входной параметр, так что предлагаю убрать

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +    public void parse(String fileName) {
нехорошо, что этот метод по сути выполняет две функции: открывает файл  и парсит. Менять не надо, но в одной из следующих лаб, мы посмотрим, как такое делается обычно

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +    public void parse(String fileName) {
ещё, если ты не думаешь о том, как этот метод будет вести себя при некорректном входном файле, нужно написать в документации, что ты снимаешь с себя ответственность. Если думаешь, напиши, что будет)

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +        if (this.getClass() != o.getClass()) return false;
вроде ещё проверки на null в equals делаются
![image](https://github.com/user-attachments/assets/56fdbecd-e9c5-4567-9c3c-fc568d7e9772)

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphMatrixAdjacency.java
> +        return vertices;
clone

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphMatrixAdjacency.java
> +    public boolean equals(Object o) {
hashcode

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphMatrixAdjacency.java
> +    private String newLine(){
можно сделать класс Utils, в котором можно сделать статический метод с таким поведением. Или как-то иначе избавиться от дублирования этого метода

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphSorter.java
> +    ArrayList<Vertex<String>> vertices = new ArrayList<>();
мне кажется, тебе тут не сильно нужно состояние, можно просто сделать статические методы, так как это алгоритм

2024-09-25 15:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/Vertex.java
> +    int color;
у меня есть подозрение, что это это поле не должно быть здесь. Его использует только топсорт, но должен ли топсорт или любой другой алгоритм менять вершины графа? а если сторонний алгоритм не перекрасит вершины в белый после выполнения? добавляются лишние места для ошибок, поэтому цвета я бы хранила в методе топсорт как хэшмап

2024-09-26 01:59 UTC, yura-poj commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +    public boolean equals(Object o) {
это плохо? или просто как факт

2024-09-26 02:01 UTC, yura-poj commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphMatrixAdjacency.java
> +    public boolean equals(Object o) {
мне надо еще hascode написать здесь?

2024-09-26 02:43 UTC, yura-poj commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphSorter.java
> +    ArrayList<Vertex<String>> vertices = new ArrayList<>();
не понял, убрать класс и распихать методы по графам?

2024-09-26 03:18 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphListAdjacency.java
> +    public boolean equals(Object o) {
это часть контракта этого метода, которая у тебя нарушается, поэтому да, плохо не определять hashCode
Вот тут
https://javarush.com/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam
хорошо написано, что может пойти не так
![image](https://github.com/user-attachments/assets/26638f92-eac7-4e29-bce5-619b328ffdce)
и ещё вот ссылка на документацию
https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-
![image](https://github.com/user-attachments/assets/b9666d5c-2a5f-49ec-b05c-d2230a595ab3)

2024-09-26 03:19 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphMatrixAdjacency.java
> +    public boolean equals(Object o) {
ага

2024-09-26 03:25 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphSorter.java
> +    ArrayList<Vertex<String>> vertices = new ArrayList<>();
не, можно сделать класс только со статическими методами. Но это спорно, просто как с сортировкой из первой задачи мне кажется тут лучше не делать поля, потому что по сути это не объект, у которого есть особое состояние, а просто алгоритм. А состояние там, где оно не нужно, может порождать ошибки, потому что надо думать, что будет если несколько раз вызвать  метод объекта и т.д.

В целом можно оставить так, но нужно тогда продумать, как пользователь будет использовать метод и обезопасить его от этих ошибок, хотя бы в документации

2024-09-30 07:28 UTC, galinabykova requested changes
в этой лабе осталось немножко)

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/Edge.java
> +    Vertex<T> from;
private

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/Edge.java
> +    Vertex<T> to;
private

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphSorter.java
> +    ArrayList<Vertex<T>> vertices;
private

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphSorter.java
> +    HashMap<Vertex<T>, Integer> colors;
private

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphSorter.java
> +    Graph<T> graph;
private

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/Vertex.java
> +    T name;
private

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphSorter.java
> +    public ArrayList<Vertex<T>> topologicalSort(Graph<T> graph) {
можно ли вызывать два раза topologicalSort у одного объекта? Если нет, это надо прописать в документации

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/test/java/ru/nsu/pozhidaev/GraphSorterTest.java
> +class GraphSorterTest {
тут можно было бы использовать параметризированные тесты, чтобы не писать отдельно тест для каждой реализации интерфейса Graph

```java
    @ParameterizedTest
    @ArgumentsSource(testArgumentsProvider.class)
    void testAdjacencyMatrixGraph(Graph<String> graph) {
        Main.readDataForGraphFromFile(graph, "input.txt");
        var result = graph.constructShortestDistances("C");
        Assertions.assertEquals(result, getPredictedMap());
    }

    static class testArgumentsProvider implements ArgumentsProvider {
        @Override
        public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
            return Stream.of(
                    Arguments.of(new IncidentMatrixGraph<String>()),
                    Arguments.of(new AdjacencyMatrixGraph<String>())
            );
        }
    }
```

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/test/java/ru/nsu/pozhidaev/GraphSorterTest.java
> +class GraphSorterTest {
менять не надо, просто для расширения кругозора

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/GraphMatrixAdjacency.java
> +    private Scanner scanner;
кажется, забыл убрать само поле

2024-09-30 07:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/pozhidaev/Utilities.java
> +public class Utilities {
обычно в утилитах все методы статические и это воспринимается как солянка полезных алгоритмов. У тебя немного не так. Менять не надо, просто делюсь ощущением

2024-09-30 15:56 UTC, galinabykova requested changes
только reviewdog)

2024-09-30 16:27 UTC, galinabykova approved these changes

2024-10-07 11:11 UTC, merged