Task_1_2_2
yura-poj/OOP pull request #19
Opened 2024-09-26 06:11 UTC by yura-poj

2024-09-26 08:17 UTC, galinabykova requested changes

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +    Set<T> keys;
сделай все поля приватными)

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +        return keys;
ты тут возвращаешь ссылку на своё поле. Получатель результата может делать после этого всё, что угодно с твоим сетом. Предлагаю убрать этот метод, так как без него можно легко обойтись

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +    Set<T> keys;
а ещё мне кажется, что использовать хэшсет при реализации хэш-таблицы не очень хорошая идея. Тип это +- один алгоритм

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +    Set<T> keys;
Цитата из документации
https://docs.oracle.com/javase/8/docs/api/java/util/HashSet.html
This class implements the Set interface, backed by a hash table (actually a HashMap instance).

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +        int id = jenkinsHash(key, keySize);
тут логично использовать не твою хэш-функцию, а хэш-функцию класса T (метод hashcode)

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +        int id = jenkinsHash(key, keySize);
и от неё процент брать

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +        String result = "";
тут у тебя сложное конструирование строки. Используй StringBuilder, потому что String не изменяемо, и у тебя тут будет много лишних копирований
https://javarush.com/groups/posts/2351-znakomstvo-so-string-stringbuffer-i-stringbuilder-v-java
![Uploading image.png…]()

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +    public void print() {
имхо, можно было не делать этот метод, но он может и быть

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +    public boolean equals(Object o) {
нужно реализовать hashCode

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +public class HashTable<T, D> {
твой класс должен реализовывать интерфейс Iterable
https://javarush.com/quests/lectures/questcollections.level07.lecture03
вот для этого условия
![image](https://github.com/user-attachments/assets/293277b0-0f0f-4634-b687-c6824799e478)
Также обрати внимание на ConcurrentModificationException. Советую перед его реализацией почитать документацию к этому исключению, это поможет продумать, как его реализовывать

2024-09-26 08:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +public class HashTable<T, D> {
ожидаю, что у тебя появится тест с forEach пробегом по твоей мапке

2024-09-27 06:16 UTC, yura-poj commented
Я случайно реализовал Iterator вместе Iterable, я же надеюсь не придется переделывать ;(

2024-09-27 06:41 UTC, galinabykova commented
> Я случайно реализовал Iterator вместе Iterable, я же надеюсь не придется переделывать ;(

к сожалению, придётся, так как это одна из основных штук в этой лабе. У тебя должен быть и Iterator, и Iterable, два объекта. Нужно всё, относящееся к итератору, перенести в отдельный класс, а саму таблицу сделать Iterable. Это несложно сделать.

Также не забудь про ConcurrentModificationException. Его должен бросать итератор в определённой ситуации

2024-09-27 06:43 UTC, galinabykova requested changes

2024-09-27 06:43 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +    public boolean equals(Object o) {
для этого класса нужно сделать метод hashCode, так как здесь есть equals. Сейчас ты нарушаешь контракт

2024-09-27 14:38 UTC, yura-poj commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +    public boolean equals(Object o) {
я не понимаю хэшкод для самого класса hashtable?

2024-09-27 14:39 UTC, yura-poj commented
> > Я случайно реализовал Iterator вместе Iterable, я же надеюсь не придется переделывать ;(
> 
> к сожалению, придётся, так как это одна из основных штук в этой лабе. У тебя должен быть и Iterator, и Iterable, два объекта. Нужно всё, относящееся к итератору, перенести в отдельный класс, а саму таблицу сделать Iterable. Это несложно сделать.
> 
> Также не забудь про ConcurrentModificationException. Его должен бросать итератор в определённой ситуации

это как два имлемента сделать?

2024-09-27 16:07 UTC, galinabykova commented
> > > Я случайно реализовал Iterator вместе Iterable, я же надеюсь не придется переделывать ;(
> > 
> > 
> > к сожалению, придётся, так как это одна из основных штук в этой лабе. У тебя должен быть и Iterator, и Iterable, два объекта. Нужно всё, относящееся к итератору, перенести в отдельный класс, а саму таблицу сделать Iterable. Это несложно сделать.
> > Также не забудь про ConcurrentModificationException. Его должен бросать итератор в определённой ситуации
> 
> это как два имлемента Iterable и Iterator сделать?

нужно создать отдельный класс, который будет реализовывать iterator. Объект этого класса будет возвращать метод iterator HashTable, которая реализует Iterable

2024-09-27 16:07 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +    public boolean equals(Object o) {
да

2024-09-28 10:24 UTC, galinabykova requested changes
ага, вот так. Нужно ещё разобраться с ConcurrentModificationException и тесты доделать

2024-09-28 10:24 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +        public void forEach(Consumer<? super Structure<T, D>> action) {
криво сформулировала, я имела ввиду не отдельный метод, а foreach loop, который ты сможешь использовать, когда сделаешь итератор
https://docs.oracle.com/javase/8/docs/technotes/guides/language/foreach.html
надо сделать на него тест

2024-09-28 10:24 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/pozhidaev/HashTable.java
> +                System.out.println("You can not modify collection during iterating");
ты должен не обрабатывать его, а бросать в ситуациях, когда пользователь пытается итерироваться по коллекции, которая была изменена. Нужно определять, что коллекция изменилась и бросать это исключение (бросать должны методы итератора, а не метод изменения хэш-таблицы)

2024-10-01 15:17 UTC, galinabykova approved these changes

2024-10-07 11:12 UTC, merged