Task_1_3_1
yura-poj/OOP pull request #20
Opened 2024-09-27 02:56 UTC by yura-poj

2024-09-27 06:00 UTC, galinabykova requested changes

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/SearchSubstring.java
> +    Utilities utilities;
private

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/SearchSubstring.java
> +    ArrayList<Integer> results = new ArrayList<>();
private

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/SearchSubstring.java
> +        char ch = 0;
хотелось бы более осмысленные имена

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/Utilities.java
> +    private Scanner scanner;
кажется, эта штука не используется

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/Utilities.java
> +    public int newChar() throws IOException {
мне кажется, этот метод легко переписать без рекурсии

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/SearchSubstring.java
> +    Utilities utilities;
здесь ты привязываешься к тому, что ты читаешь данные именно из файла. Предлагаю не делать этого, а использовать иерархичность потоков ввода-вывода в Java

прочитай первый раздел вот тут https://metanit.com/java/tutorial/6.1.php
![image](https://github.com/user-attachments/assets/969e111e-edf1-4bd1-a7a2-da603460584f)

нужно сделать в этом классе метод, которому после предварительной подготовки можно скормить файл, строку, ресурс

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/SearchSubstring.java
> +    Utilities utilities;
этот код я не тестировала, но примерно так оно будет выглядеть. Ты создашь метод, которому будет не важно, с каким Reader иметь дело

```java
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }

    public static ArrayList<Integer> search(Reader reader, String substring) throws IOException {
        ArrayList<Integer> result = new ArrayList<>();
        // useful work;
        return result;
    }

    public static ArrayList<Integer> searchFile(String fileName, String substring) throws IOException {
        var reader = new BufferedReader(new FileReader(fileName));
        var result = search(reader, substring);
        return result;
    }

    public static ArrayList<Integer> searchResource(String fileName, String substring) throws IOException {

        InputStreamReader reader = new InputStreamReader(Main.class.getClassLoader().getResourceAsStream(
                "bookmark-example.xml"));
        var result =  search(reader, substring);
        return result;
    }
}
```

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/pozhidaev/test.txt
в этой задаче мы учимся работать ресурсы. Все заранее подготовленные (не генерируемые) файлы должны быть в ресурсах
https://docs.oracle.com/javase/8/docs/technotes/guides/lang/resources.html

2024-09-27 06:00 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/pozhidaev/SearchSubstringTest.java
нужны тесты на крайние случаи, тесты с символами не из ascii (например, кириллица и иероглифы), тест, показывающий, что твоя программа может работать с файлом, который не влазит в оперативную память (этот файл не нужно грузить в репозиторий, нужно либо генерировать в тесте большой файл (его надо не забыть удалить), либо создать поток "симулирующий" большой файл

2024-09-27 06:38 UTC, yura-poj commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/SearchSubstring.java
> +    Utilities utilities;
Может надо   public static ArrayList<Integer> search(InputStream inputStream, String substring) throws IOException 
или перегруженные методы

2024-09-27 06:44 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/pozhidaev/SearchSubstring.java
> +    Utilities utilities;
Да, так тоже можно) Главное, чтобы у тебя была одна реализация алгоритма

2024-10-01 16:53 UTC, galinabykova requested changes

2024-10-01 16:53 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/pozhidaev/SearchSubstringTest.java
> +        File file = new File("./src/test/resources/test1.txt");
не так, для ресурсов всё же нужно использовать специальный синтаксис. Ты тут используешь знание о том, где у тебя лежит твой класс файл, что в общем случае неверно. Твоя сборка должна существовать без твоего кода. Основная фишка ресурсов в том, что они являются частью сборки и попадают, например, в jar. 

Посмотри, как сделано тут
https://sky.pro/wiki/java/poluchenie-puti-k-resursu-v-jar-fayle-java-resheniya-i-oshibki/
здесь используются методы, которые надо использовать
![image](https://github.com/user-attachments/assets/1a77d529-8f57-4416-995b-8afaeab8e04b)
в статическом методе можно написать НазваниеКласса.class вместо getClass

Объяснение, зачем оно надо, тут 
https://skipy-ru.livejournal.com/5343.html
мне нравится больше
![image](https://github.com/user-attachments/assets/f39f792c-7616-4930-93cc-d4c543baca11)

2024-10-02 02:33 UTC, galinabykova approved these changes
Прочитай комментарий, править не обязательно, потому что там просто путь к директории поменять, не то чтобы это полезно с образовательной точки зрения, но осознать его надо

2024-10-02 02:33 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/pozhidaev/SearchSubstringTest.java
> +        File file = new File("./src/test/resources/test1.txt");
лучше не писать в ресурсы, ресурсы нужны для постоянных не меняющихся файлов, а не для генерируемых. Если скопировать твою сборку в другое место, она, скорее всего, не найдёт этот путь. Лучше создать файл просто в рабочей директории

2024-10-07 11:30 UTC, merged