Task_1_4_1
yura-poj/OOP pull request #21
Opened 2024-10-01 16:20 UTC by yura-poj

2024-10-02 04:15 UTC, yura-poj commented
подходящая структура?

2024-10-02 04:48 UTC, galinabykova requested changes
Примерно, да, написала небольшие замечания

2024-10-02 04:48 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
не поняла точно, что здесь. Если речь идёт об экзаменах, зачётах, диф. зачётах, лучше сделать для них Enum, так как типов фиксированное небольшое число.

2024-10-02 04:48 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
но непонятно, что такое оценка у зачёта. Или тебе только диф зачёты нужны для расчёта и остальное ты не учитываешь?

2024-10-02 04:48 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    public int[] getGrades(String type) {
мне кажется, можно вместо этого метода сделать getGrade(int semester, String type). Не вижу тут значимых причин возвращать ссылочный тип

2024-10-02 04:48 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/RecordBook.java
наверно, ещё должен быть метод добавления новой оценки)

2024-10-02 04:48 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
я бы оценки сделала или классом, или Enum. Если решишь оставить просто int, корректно обработай ситуацию, когда пользователь пытается добавить некорректную оценку

2024-10-02 05:37 UTC, yura-poj commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/RecordBook.java
да вроде есть в обьекте сабджект, или надо чтобы в recordbook тоже надо

2024-10-02 05:39 UTC, yura-poj commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
ну по факту у меня Есть recordbook которая имеет лист subject и внутри предмета уже есть типы зачетов с оценками

2024-10-02 05:40 UTC, yura-poj commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
что вы имеете ввиду под оценка зачета?

2024-10-02 05:40 UTC, yura-poj commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
А если будет Enum пользователь будет выбирать по строке или как?

2024-10-02 05:47 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
у тебя пользователь будет работать с твоей библиотекой, а не с консольным приложением, можно просто ему дать Enum, пусть его использует. Это удобнее, чем строка: в строке можно ошибиться в символах и не понять это сразу, а с енамом в случае ошибки программа просто не скомпилируется

2024-10-02 05:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
по поводу оценки зачёта, у нас в программе есть не диф зачёты (например, физра) и мне непонятно, как с ними будет работать твоя программа

2024-10-02 05:53 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/RecordBook.java
надо, чтобы у тебя был способ после каждого нового семестра добавлять оценки как-либо. Сейчас в зачётную книжку никак не добавить ни предмет, ни оценку. Когда будешь добавлять метод, обрати внимание, что должна быть возможность сначала добавить одну оценку за предмет, а потом другую. Также, наверно, ты должен знать номер текущего семестра, чтобы рассчитывать, может ли студент рассчитывать на перевод на бюджет

2024-10-02 06:05 UTC, yura-poj commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    private HashMap<String,int[]> types;
> по поводу оценки зачёта, у нас в программе есть не диф зачёты (например, физра) и мне непонятно, как с ними будет работать твоя программа

забыл про это, ну тогда да придется класс еще один делать

2024-10-04 07:49 UTC, galinabykova requested changes

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Grade.java
> +    public boolean equals(Object o) {
hashcode

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Grade.java
> +    private boolean success;
не уверена, что есть смысл делать под это отдельное поле, если "успех" вычисляется в один if. Исправлять не надо, просто мысль

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Grade.java
> +    private GradeType type;
можно сделать final. Я исповедую религию, в которой всё, что можно делать final, надо делать final

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Student.java
> +    private RecordBook recordBook;
тут тоже можно сделать final, так как final для ссылочных объектов говорит только о том,  что ссылка не будет подменена, а изменения объекта для final норм

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +        return new ArrayList<>(grades);
здесь у тебя копирование не полное, посмотри пример
https://onlinegdb.com/rCZq3Sz1X
также, хотя я вам говорила, что лучше возвращать копию, это спорный вопрос. С одной стороны, копия защищает поле, с другой - расходы по памяти будут увеличатся, поэтому нужно искать баланс.

Часто, чтобы его не искать, можно подумать - а зачем мне вообще возвращать эту ссылку? у тебя, например, этот метод используется только тут
![image](https://github.com/user-attachments/assets/3533723b-d7be-4cf4-8b33-29903d36db82)
и на самом деле можно сделать метод в Subject, который возвращает поток

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +        return new ArrayList<>(grades);
то есть в метод в Subject вынести в метод
![image](https://github.com/user-attachments/assets/de9333ca-4772-44bf-9498-8ab9f3684cca)
а в лямбде просто написать s -> s.nameMethodFromSubject();

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +            return;
Интересно, что тут не исключение, а return. Если хочешь так оставить, пропиши в документацию эту особенность.

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +            return;
И объясни, почему так

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +    public void setGrade(int grade, int semester, GradeType type) throws NoSuchSemesterYet {
на самом деле, можно не указывать семестр, а просто в последний оценки добавлять, но твоё решение более гибкое, хоть и менее удобное, так что менять не надо)

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/RecordBook.java
> +                        .size() > 0.75));
магическая константа

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/pozhidaev/GradeTest.java
> +    Grade grade1;
нужны более осмысленные названия. Кстати, можно написать так
`final Grade grade = new Grade(5, GradeType.Exam);`

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/pozhidaev/GradeTest.java
> +    Grade grade1;
тогда setUp не нужен

2024-10-04 07:49 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/pozhidaev/RecordBookTest.java
> +    void chanceToGetRedDiplomaTrue() throws Subject.NoSuchSemesterYet,
протестируй разные случаи с красным дипломом: когда средний балл не подходит, когда диплом на 4, когда тройка есть

2024-10-04 13:44 UTC, yura-poj commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +            return;
> И объясни, почему так

да просто лень было, как то муторно исключения создавать.

2024-10-04 13:49 UTC, yura-poj commented on Task_1_4_1/src/main/java/ru/nsu/pozhidaev/Subject.java
> +        return new ArrayList<>(grades);
я читал про не полное копирование, но не понимал как это, спасибо

2024-10-05 03:38 UTC, galinabykova requested changes
reviewdog

2024-10-05 08:40 UTC, galinabykova approved these changes

2024-10-07 11:32 UTC, merged